/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryBreakdown = IDL.Record({
  'other' : IDL.Float64,
  'food' : IDL.Float64,
  'travel' : IDL.Float64,
  'bills' : IDL.Float64,
  'shopping' : IDL.Float64,
  'health' : IDL.Float64,
});
export const Category = IDL.Text;
export const CreateExpenseInput = IDL.Record({
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Float64,
});
export const ExpenseId = IDL.Text;
export const Timestamp = IDL.Int;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'category' : Category,
  'amount' : IDL.Float64,
});
export const Insight = IDL.Record({
  'insightType' : IDL.Text,
  'message' : IDL.Text,
});
export const UpdateExpenseInput = IDL.Record({
  'id' : ExpenseId,
  'date' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'category' : Category,
  'amount' : IDL.Float64,
});
export const WeeklyTrend = IDL.Record({
  'percentageChange' : IDL.Float64,
  'currentWeekTotal' : IDL.Float64,
  'previousWeekTotal' : IDL.Float64,
});

export const idlService = IDL.Service({
  'categoryBreakdown' : IDL.Func([], [CategoryBreakdown], ['query']),
  'createExpense' : IDL.Func([CreateExpenseInput], [Expense], []),
  'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
  'getBudget' : IDL.Func([], [IDL.Float64], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [IDL.Opt(Expense)], ['query']),
  'getInsights' : IDL.Func([], [IDL.Vec(Insight)], ['query']),
  'getSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'monthlySpending' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'predictNextMonth' : IDL.Func([], [IDL.Float64], ['query']),
  'setBudget' : IDL.Func([IDL.Float64], [], []),
  'totalSpending' : IDL.Func([], [IDL.Float64], ['query']),
  'updateExpense' : IDL.Func([UpdateExpenseInput], [IDL.Bool], []),
  'weeklyTrend' : IDL.Func([], [WeeklyTrend], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryBreakdown = IDL.Record({
    'other' : IDL.Float64,
    'food' : IDL.Float64,
    'travel' : IDL.Float64,
    'bills' : IDL.Float64,
    'shopping' : IDL.Float64,
    'health' : IDL.Float64,
  });
  const Category = IDL.Text;
  const CreateExpenseInput = IDL.Record({
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const ExpenseId = IDL.Text;
  const Timestamp = IDL.Int;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const Insight = IDL.Record({
    'insightType' : IDL.Text,
    'message' : IDL.Text,
  });
  const UpdateExpenseInput = IDL.Record({
    'id' : ExpenseId,
    'date' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'category' : Category,
    'amount' : IDL.Float64,
  });
  const WeeklyTrend = IDL.Record({
    'percentageChange' : IDL.Float64,
    'currentWeekTotal' : IDL.Float64,
    'previousWeekTotal' : IDL.Float64,
  });
  
  return IDL.Service({
    'categoryBreakdown' : IDL.Func([], [CategoryBreakdown], ['query']),
    'createExpense' : IDL.Func([CreateExpenseInput], [Expense], []),
    'deleteExpense' : IDL.Func([ExpenseId], [IDL.Bool], []),
    'getBudget' : IDL.Func([], [IDL.Float64], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [IDL.Opt(Expense)], ['query']),
    'getInsights' : IDL.Func([], [IDL.Vec(Insight)], ['query']),
    'getSuggestions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'monthlySpending' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
    'predictNextMonth' : IDL.Func([], [IDL.Float64], ['query']),
    'setBudget' : IDL.Func([IDL.Float64], [], []),
    'totalSpending' : IDL.Func([], [IDL.Float64], ['query']),
    'updateExpense' : IDL.Func([UpdateExpenseInput], [IDL.Bool], []),
    'weeklyTrend' : IDL.Func([], [WeeklyTrend], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };