/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = string;
export interface CategoryBreakdown {
  'other' : number,
  'food' : number,
  'travel' : number,
  'bills' : number,
  'shopping' : number,
  'health' : number,
}
export interface CreateExpenseInput {
  'date' : string,
  'note' : [] | [string],
  'category' : Category,
  'amount' : number,
}
export interface Expense {
  'id' : ExpenseId,
  'date' : string,
  'note' : [] | [string],
  'createdAt' : Timestamp,
  'category' : Category,
  'amount' : number,
}
export type ExpenseId = string;
export interface Insight { 'insightType' : string, 'message' : string }
export type Timestamp = bigint;
export interface UpdateExpenseInput {
  'id' : ExpenseId,
  'date' : string,
  'note' : [] | [string],
  'category' : Category,
  'amount' : number,
}
export interface WeeklyTrend {
  'percentageChange' : number,
  'currentWeekTotal' : number,
  'previousWeekTotal' : number,
}
export interface _SERVICE {
  'categoryBreakdown' : ActorMethod<[], CategoryBreakdown>,
  'createExpense' : ActorMethod<[CreateExpenseInput], Expense>,
  'deleteExpense' : ActorMethod<[ExpenseId], boolean>,
  'getBudget' : ActorMethod<[], number>,
  'getExpense' : ActorMethod<[ExpenseId], [] | [Expense]>,
  'getInsights' : ActorMethod<[], Array<Insight>>,
  'getSuggestions' : ActorMethod<[], Array<string>>,
  'listExpenses' : ActorMethod<[], Array<Expense>>,
  'monthlySpending' : ActorMethod<[string], number>,
  'predictNextMonth' : ActorMethod<[], number>,
  'setBudget' : ActorMethod<[number], undefined>,
  'totalSpending' : ActorMethod<[], number>,
  'updateExpense' : ActorMethod<[UpdateExpenseInput], boolean>,
  'weeklyTrend' : ActorMethod<[], WeeklyTrend>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];