/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Category = string;
export interface CategoryBreakdown {
    other: number;
    food: number;
    travel: number;
    bills: number;
    shopping: number;
    health: number;
}
export type Timestamp = bigint;
export interface CreateExpenseInput {
    date: string;
    note?: string;
    category: Category;
    amount: number;
}
export interface WeeklyTrend {
    percentageChange: number;
    currentWeekTotal: number;
    previousWeekTotal: number;
}
export type ExpenseId = string;
export interface Expense {
    id: ExpenseId;
    date: string;
    note?: string;
    createdAt: Timestamp;
    category: Category;
    amount: number;
}
export interface Insight {
    insightType: string;
    message: string;
}
export interface UpdateExpenseInput {
    id: ExpenseId;
    date: string;
    note?: string;
    category: Category;
    amount: number;
}
export interface backendInterface {
    categoryBreakdown(): Promise<CategoryBreakdown>;
    createExpense(input: CreateExpenseInput): Promise<Expense>;
    deleteExpense(id: ExpenseId): Promise<boolean>;
    getBudget(): Promise<number>;
    getExpense(id: ExpenseId): Promise<Expense | null>;
    getInsights(): Promise<Array<Insight>>;
    getSuggestions(): Promise<Array<string>>;
    listExpenses(): Promise<Array<Expense>>;
    monthlySpending(month: string): Promise<number>;
    predictNextMonth(): Promise<number>;
    setBudget(amount: number): Promise<void>;
    totalSpending(): Promise<number>;
    updateExpense(input: UpdateExpenseInput): Promise<boolean>;
    weeklyTrend(): Promise<WeeklyTrend>;
}
import type { Category as _Category, CreateExpenseInput as _CreateExpenseInput, Expense as _Expense, ExpenseId as _ExpenseId, Timestamp as _Timestamp, UpdateExpenseInput as _UpdateExpenseInput } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async categoryBreakdown(): Promise<CategoryBreakdown> {
        if (this.processError) {
            try {
                const result = await this.actor.categoryBreakdown();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.categoryBreakdown();
            return result;
        }
    }
    async createExpense(arg0: CreateExpenseInput): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.createExpense(to_candid_CreateExpenseInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Expense_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExpense(to_candid_CreateExpenseInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Expense_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteExpense(arg0: ExpenseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async getBudget(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget();
            return result;
        }
    }
    async getExpense(arg0: ExpenseId): Promise<Expense | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInsights(): Promise<Array<Insight>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInsights();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInsights();
            return result;
        }
    }
    async getSuggestions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuggestions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuggestions();
            return result;
        }
    }
    async listExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.listExpenses();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listExpenses();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async monthlySpending(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.monthlySpending(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.monthlySpending(arg0);
            return result;
        }
    }
    async predictNextMonth(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.predictNextMonth();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.predictNextMonth();
            return result;
        }
    }
    async setBudget(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBudget(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBudget(arg0);
            return result;
        }
    }
    async totalSpending(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.totalSpending();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.totalSpending();
            return result;
        }
    }
    async updateExpense(arg0: UpdateExpenseInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpense(to_candid_UpdateExpenseInput_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpense(to_candid_UpdateExpenseInput_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async weeklyTrend(): Promise<WeeklyTrend> {
        if (this.processError) {
            try {
                const result = await this.actor.weeklyTrend();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.weeklyTrend();
            return result;
        }
    }
}
function from_candid_Expense_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Expense]): Expense | null {
    return value.length === 0 ? null : from_candid_Expense_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpenseId;
    date: string;
    note: [] | [string];
    createdAt: _Timestamp;
    category: _Category;
    amount: number;
}): {
    id: ExpenseId;
    date: string;
    note?: string;
    createdAt: Timestamp;
    category: Category;
    amount: number;
} {
    return {
        id: value.id,
        date: value.date,
        note: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.note)),
        createdAt: value.createdAt,
        category: value.category,
        amount: value.amount
    };
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n3(_uploadFile, _downloadFile, x));
}
function to_candid_CreateExpenseInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateExpenseInput): _CreateExpenseInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateExpenseInput_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateExpenseInput): _UpdateExpenseInput {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: string;
    note?: string;
    category: Category;
    amount: number;
}): {
    date: string;
    note: [] | [string];
    category: _Category;
    amount: number;
} {
    return {
        date: value.date,
        note: value.note ? candid_some(value.note) : candid_none(),
        category: value.category,
        amount: value.amount
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ExpenseId;
    date: string;
    note?: string;
    category: Category;
    amount: number;
}): {
    id: _ExpenseId;
    date: string;
    note: [] | [string];
    category: _Category;
    amount: number;
} {
    return {
        id: value.id,
        date: value.date,
        note: value.note ? candid_some(value.note) : candid_none(),
        category: value.category,
        amount: value.amount
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
